# Whether to stop the commit if any of the hooks fail
fail_fast: false

# The list of hooks that are run by pre-commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: check-added-large-files
        args: [--maxkb 100KB]
