# Minimum pre-commit version required
minimum_pre_commit_version: 3.2.0

# Whether to stop the commit if any of the hooks fail
fail_fast: false

# The list of hooks that are run by pre-commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: name-tests-test
      - id: check-added-large-files
        args: [--maxkb 100KB]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.9
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        # The entry point for the hook, in this case, mypy.
        entry: mypy --show-error-codes --pretty .
        language: system
        pass_filenames: false
        files: ^src/.*\.py$
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        # The entry point for the hook, in this case, pytest.
        entry: >
          pytest -k robust -v --cov
          --cov-branch --cov-fail-under=80
        language: system
        pass_filenames: false
