

fail_fast: false

repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.0'  # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        name: poetry-export-requirements
        args: ["-f", "requirements.txt", "-o", "requirements.txt", "--without-hashes"]
      - id: poetry-export
        name: poetry-export-dev-requirements
        args: ["-f", "requirements.txt", "-o", "requirements-dev.txt", "--without-hashes", "--with", "dev"]
