# Minimum pre-commit version required
minimum_pre_commit_version: 3.2.0

# Whether to stop the commit if any of the hooks fail
fail_fast: false

# The list of hooks that are run by pre-commit
repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.0'  # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        name: poetry-export-requirements
        args: ["-f", "requirements.txt", "-o", "requirements.txt", "--without-hashes"]
        always_run: true
      - id: poetry-export
        name: poetry-export-dev-requirements
        args: ["-f", "requirements.txt", "-o", "requirements-dev.txt", "--without-hashes", "--with", "dev"]
        always_run: true