[tool.ruff]
line-length = 88        # Not relevant
target-version = "py38" # Not relevant
src = ["tests", "docs"] # Not relevant

[tool.ruff.lint]
ignore = ["D100", "D104", "N999", "D401", "C901", "S311", "S101"]
select = ["F", "E", "W", "C90", "S", "I", "N", "D", "UP"]

[tool.ruff.lint.pydocstyle]
convention = "pep257" # Not relevant

[tool.mypy]
exclude="venv"

[tool.pytest.ini_options]
markers = [
    "naive: very naive method that is not recommended",
    "smart: smart method that is recommended",
    "robust: robust method that covers all edge cases",
]
